name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build distributions
      run: |
        chmod +x scripts/build_distributions.sh
        ./scripts/build_distributions.sh
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          distributions/*.dmg
          distributions/*.exe
          docs/SECURITY.md
          docs/BUILD_SUMMARY.md
          docs/WINDOWS_INSTALLATION_GUIDE.md
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
